### ISSUE TITLE
Question: What need to be done to install GUpnp binding?

### ISSUE THREAD

**Issue by jondoe1337** [rokm/exaile-dlna-collection#1]
I would like to know what kind of packages are needed in order to install those bindings on debian/ubuntu:
```
GIR bindings for GUPnP library
GIR bindings for GUPnPAV library
```

**Comment by jondoe1337** [comment]
I'm guessing: `gir1.2-gupnp-1.0 gir1.2-gupnp-av-1.0`

**Comment by rokm** [comment]
> I'm guessing: `gir1.2-gupnp-1.0 gir1.2-gupnp-av-1.0`

Indeed, the bindings should be provided by those packages.

**Comment by jondoe1337** [comment]
Yep works!
